# Generated by Django 3.1.5 on 2021-01-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20210108_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
